version: '3'

services:
  client:
    build:
      context: ./client   # Specify the path to the Dockerfile
      dockerfile: Dockerfile  # Dockerfile name
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
